// crypto-ts: cryptography primitives and wrappers
// Copyright 2026 Dark Bio AG. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

import init, {
  hkdf_key,
  hkdf_extract,
  hkdf_expand,
} from "./wasm/darkbio_crypto_wasm.js";

let initialized = false;

async function ensureInit(): Promise<void> {
  if (!initialized) {
    await init();
    initialized = true;
  }
}

/**
 * Derive a key from secret, salt, and info using HKDF-SHA256.
 *
 * @param secret - The input keying material
 * @param salt - Optional salt value (can be empty)
 * @param info - Optional context/application-specific info (can be empty)
 * @param outLen - Desired output length in bytes (max 8160)
 * @returns The derived key
 */
export async function key(
  secret: Uint8Array,
  salt: Uint8Array,
  info: Uint8Array,
  outLen: number
): Promise<Uint8Array> {
  await ensureInit();
  return new Uint8Array(hkdf_key(secret, salt, info, outLen));
}

/**
 * Extract a pseudorandom key from secret and salt using HKDF-SHA256.
 *
 * Only use this if you need to reuse the extracted key with multiple
 * expand invocations. Most scenarios should use `key` instead.
 *
 * @param secret - The input keying material
 * @param salt - Optional salt value (can be empty)
 * @returns A 32-byte pseudorandom key
 */
export async function extract(
  secret: Uint8Array,
  salt: Uint8Array
): Promise<Uint8Array> {
  await ensureInit();
  return new Uint8Array(hkdf_extract(secret, salt));
}

/**
 * Expand a pseudorandom key with info using HKDF-SHA256.
 *
 * The prk should have been generated by `extract` or be a uniformly
 * random 32-byte key.
 *
 * @param prk - A 32-byte pseudorandom key
 * @param info - Optional context/application-specific info (can be empty)
 * @param outLen - Desired output length in bytes (max 8160)
 * @returns The derived key
 */
export async function expand(
  prk: Uint8Array,
  info: Uint8Array,
  outLen: number
): Promise<Uint8Array> {
  await ensureInit();
  return new Uint8Array(hkdf_expand(prk, info, outLen));
}
